name: Test SSH Connection Only

on:
  push:
    branches: [ dev/pipelineTry]  # Test on both branches
jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Test SSH with custom port
      run: |
        echo "Testing connection to ${{ secrets.SSH_HOST }}:${{ secrets.SSH_PORT }}"
        ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
          "echo '✅ Success! Current directory:'; pwd; echo 'User:'; whoami"
